From: Eneg Kerman (KEI representative)
To: Gene Kerman (KSC flight director)
SUBJECT: Atmospheric Pressure Scan
----
A new PresMat Barometer forgotten near one of the liquid fuel tanks and suddenly found by a janitor is showing increased pressure, but only near that tank. Janitor says it is because the tank is leaking and liquid fuel is evaporating, thus affecting the barometer's readings. But who would listen to him? I bet he broke the barometer and does not want to confess.
