From: Gene Kerman (KSC flight director)
To: Eneg Kerman (KEI representative)
SUBJECT: Crew Report
----
As we were planning our first manned flight we've came to an interesting idea we called "Crew Report" - just a crew's assessment of a situation. Astronauts spent the whole day learning how to record a crew report. And now, while we still haven't perform any manned flights, I have a bunch of reports laying on my desk. I don't know what to do with all this stuff. I'm sending it to you, maybe your specialists will find something valuable.
