From: Gene Kerman (KSC flight director)
To: Eneg Kerman (KEI representative)
SUBJECT: Dynamic Albedo of Neutrons
----
While scientists were walking about searching for water with just the device attached to a battery, our pilots and engineers strongly demanded an extra command seat on wheels and a button to push. The readings of this strangely named device showed that we have more water in the pool than on the asphalt. In the end we did detect excessive amounts of hydrogen near the fuel tanks. I still wonder whether it was detected inside or outside the tanks.
