From: Gene Kerman (KSC flight director)
To: Eneg Kerman (KEI representative)
SUBJECT: Surface Laser Experiment
----
We shouldn't have given lasers to our astronauts, it was a disaster! Despite little discrepancy in ground composition around KSC everyone was having fun burning holes in the asphalt. Several astronauts started burning their names on the runway. Someone even wrote "Val, I love you!" along the markings, but nobody has seen the culprit. The control tower warned the incoming flights that today they will have more chances to safely land on grass than on the runway. Good news is nobody could burn a hole in the launchpad, I must commend our construction team for making at least that thing sturdy.
