From: Linus Kerman (Science division manager)
To: Eneg Kerman (KEI representative)
SUBJECT: Magnetometer BOOM
----
The magnetometer wasn't showing much outside of the buildings. All the fun started when Bill decided to get a snack. The readings started to change as he approached the fridge. We immediately took a note of this behavior and sent our astronauts on search for hidden fridges with snacks around KSC. Jebediah even found one behind a huge stack of books, Gene was very upset that his stash of yummies was exposed. At the end of the day our fitness instructor Gus Kerman commanded all the astronauts to run an extra hour on treadmills to prevent the effects of the unscheduled snacks intake.
