From: Gene Kerman (KSC flight director)
To: Eneg Kerman (KEI representative)
SUBJECT: Materials Study
----
I do not know what all these materials mean and why we must study them, but R&D keeps saying that the SC-9001 Science Jr is the most advanced science equipment in the entire universe. In my opinion, if rumors about a UFO buried under the ice of the North Pole are not just rumors and some day we find it, then all our equipment will become the least advanced in the entire universe.
