From: Gene Kerman (KSC flight director)
To: Eneg Kerman (KEI representative)
SUBJECT: Materials Study
----
I do not know what all these materials mean and why must we study them, but R&D keeps saying that SC-9001 Science Jr is the most advanced science equipment in entire universe. In my opinion if rumors about UFO buried under the ice of The Northern Pole are not just rumors and some day we will find it, then all our equipment will become least advanced in the universe.
