From: Gene Kerman (KSC flight director)
To: Eneg Kerman (KEI representative)
SUBJECT: Surface Sample
----
Today our brave astronauts were learning how to take surface samples. They dug all over the place, so now walking in KSC area is dangerous for life, because there is a big risk of falling in a really big pit. R&D rock storage is coming apart at the seams and even my desktop is littered with gravel.
